# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloWorld' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloWorld
  pod 'RxSwift',    '~> 4.0'
  pod 'SwiftIconFont'
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.5'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Kingfisher', '~> 4.0'
  pod 'RealmSwift'
  pod 'EmptyDataSet-Swift', '~> 4.0.2'
  pod 'KRPullLoader'
end
